[project]
name = "clean-vsc-exts"
version = "0.1.0"
description = "Clean up VSCode extensions"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[project.scripts]
clean-vsc-exts = "main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
